### ISSUE TITLE
Add RSS feed

### ISSUE THREAD

**Issue by xaprb** [Xe/christine.website#5]
I'd love to follow your RSS feed but I can't see one. Is there one? Can it be linked from the HEAD with the usual link-rel-stuff?

**Comment by Xe** [comment]
I hadn't considered making an RSS feed. I will see about doing that.

**Comment by Xe** [comment]
I'm deploying b4773e858a2ba338bc386cf6bc6ab5072abd9589 right now, does that do the trick?

**Comment by xaprb** [comment]
I tried adding it to feedly but it doesn't seem to find any articles in the feed. My retina-based feed validator doesn't see any problems but there could be human errors :)

**Comment by Xe** [comment]
Strange. [This template](https://github.com/Xe/christine.website/blob/master/views/blog/rss.moon) should be outputting the XML as RSS feed readers want.

**Comment by Xe** [comment]
It should be valid now

**Comment by Xe** [comment]
Feedly is generating incorrect views, but the RSS works.

**Comment by xaprb** [comment]
Thanks!

**Comment by Xe** [comment]
No problem. Always fun to do some by-hand coding for this.
